b = str(input("food :  "))
a = str(input("enter your name : "))
print(f"hello {a}")
print("you are at home!!!")
print("your mom ask you : What do you want to eat today my sweet heart?")
print(f"you say: mom i want to eat today {b}")
print("fine!!!")
print("mom can i go outside to play?")
print("ofcourse my sweet heart go !!! but dont go the room 666!!! And also dont go around of that building. ")
print("fine mom bye!!!!")